blueprint:
  name: climate_switch
  description: |
    ## Multi-on

    ## 스위치에 따라 냉난방기를 제어

    ## 매 시간 05분과 35분에 "룸 상태 switch"의 상태에 따라 "냉난방기"의 HVAC 모드를 제어

    ## Requirements
    Smartthings 에 각 냉난방기에 추가적으로 스위치를 만들고, ex) "룸1 냉난방기 상태확인"
    각 공간별 ON 자동화가 실행될 시 "룸1 냉난방기 상태확인" 을 켜고, 55분 후 "룸1 냉난방기 확인" 을 끄는 로직을 추가해줘야함!

  domain: automation
  input:
    main_st_switch:
      name: 냉난방기 ST 스위치
      selector:
        entity:
          domain: switch
    status_check_st_switch:
      name: 냉난방기 상태 스위치
      selector:
        entity:
          domain: switch
    climate_entity:
      name: 룸 or 로비 냉난방기
      selector:
        entity:
          domain: climate

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input 'main_st_switch'
  - platform: time_pattern
    minutes: '/30'
    at: ['00:05', '00:35']

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ now().minute == 5 or now().minute == 35 }}"
          - condition: state
            entity_id: !input 'status_check_st_switch'
            state: 'on'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input 'main_st_switch'
                    state: 'on'
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input 'climate_entity'
                    data:
                      hvac_mode: 'auto'
              - conditions:
                  - condition: state
                    entity_id: !input 'main_st_switch'
                    state: 'off'
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input 'climate_entity'
                    data:
                      hvac_mode: 'off'
      - conditions:
          - condition: state
            entity_id: !input 'main_st_switch'
            state: 'on'
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input 'climate_entity'
            data:
              hvac_mode: 'auto'
      - conditions:
          - condition: state
            entity_id: !input 'main_st_switch'
            state: 'off'
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input 'climate_entity'
            data:
              hvac_mode: 'off'
