blueprint:
  name: climate_switch
  description: |
    ## Multi-on

    ## 스위치에 따라 냉난방기를 제어

    ## Requirements
    Smartthings 에 각 냉난방기에 추가적으로 스위치를 만들고, ex) "룸1 냉난방기 끄기 ST"
    각 공간별 _OFF 자동화가 실행될 시 "룸1 냉난방기 끄기 ST" 를 끄는 자동화를 추가해줘야함!!
    "냉난방기 끄기 ST" 는 smartthings 자동화에만 넣고, 공간 할당은 하면 안됨!(점주가 제어하는 스위치가 아님)

  domain: automation
  input:
    main_st_switch:
      name: 냉난방기 ST 스위치
      selector:
        entity:
          domain: switch
    climate_entity:
      name: 룸 or 로비 실제 냉난방기
      selector:
        entity:
          domain: climate

mode: restart
max_exceeded: warning

trigger:
  - platform: state
    entity_id: !input "main_st_switch"

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input "main_st_switch"
            state: "on"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input "climate_entity"
            data:
              hvac_mode: "auto"
  - choose:
      - conditions:
          - condition: state
            entity_id: !input "main_st_switch"
            state: "off"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input "climate_entity"
            data:
              hvac_mode: "off"
