blueprint:
  name: sw_pc_switch
  description: |
    ## Multi-on

    ## ST 스위치에 따라 Wol, pc off 버튼으로 PC를 제어

    ## Requirements
    ex) 
    SmartThings 스위치 : 룸1 PC ST
    켜기 스위치 : 룸1 PC WOL
    끄기 버튼 : 룸1 PC 끄기
    3개 기기 연동
  domain: automation
  input:
    pc_st_switch:
      name: 룸X or 타석X PC ST
      selector:
        entity:
          domain: switch
    wol_switch:
      name: 룸X or 타석X PC WOL
      selector:
        entity:
          domain: switch
    pc_off_button:
      name: 룸X or 타석X PC 끄기
      selector:
        entity:
          domain: button

mode: restart
max_exceeded: warning

trigger:
  - platform: state
    entity_id: !input "pc_st_switch"
  - platform: state
    entity_id: !input "pc_off_button"
    attribute: available
    to: "false"

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input "pc_st_switch"
            state: "on"
        sequence:
          - service: switch.turn_on
            entity_id: !input "wol_switch"
      - conditions:
          - condition: state
            entity_id: !input "pc_st_switch"
            state: "off"
        sequence:
          - service: button.press
            entity_id: !input "pc_off_button"
